DECLARE
	numer_max NUMBER;

BEGIN
	SELECT d.DEPARTMENT_ID 
	INTO numer_max
	FROM DEPARTMENTS d 
	ORDER BY d.DEPARTMENT_ID DESC
	FETCH NEXT 1 ROWS ONLY;
	
	DBMS_OUTPUT.put_line(numer_max);

	INSERT INTO DEPARTMENTS 
	(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) 
	VALUES (numer_max + 10, 'EDUCATION', NULL, null);
END;



DECLARE
	numer_max NUMBER;
	location_id NUMBER := 3000;

BEGIN
	SELECT d.DEPARTMENT_ID 
	INTO numer_max
	FROM DEPARTMENTS d 
	ORDER BY d.	DEPARTMENT_ID DESC
	FETCH NEXT 1 ROWS ONLY;
	
	DBMS_OUTPUT.put_line(numer_max);



	INSERT INTO DEPARTMENTS 
	(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) 
	VALUES (numer_max + 10, 'EDUCATION', NULL, location_id);
END;


BEGIN
  FOR num IN 1..10 LOOP
    IF num = 4 THEN
      DBMS_OUTPUT.PUT_LINE(num);
    ELSIF num = 6 THEN
      DBMS_OUTPUT.PUT_LINE(num);
    ELSE
      INSERT INTO my_table (my_field) VALUES (num);
    END IF;
  END LOOP;
END;
